### ISSUE TITLE
Install steps

### ISSUE THREAD

**Issue by vanatomas** [woytekm/FaceOfFenix#2]
Hey, do you have instructions on putting this face on Fenix?

**Comment by woytekm** [comment]
Hi, i've just created initial binary release. You should put FaceOfFenix.prg file on your watch, in Apps folder.

**Comment by vanatomas** [comment]
@woytekm I don't see such file in this repo

**Comment by woytekm** [comment]
It's in the releases tab: https://github.com/woytekm/FaceOfFenix/releases
Direct link to the binary: https://github.com/woytekm/FaceOfFenix/releases/download/0.1/FaceOfFenix.prg

**Comment by vanatomas** [comment]
got it, thank you
